# Generated by Django 4.2.2 on 2023-06-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_description',
            new_name='inventory',
        ),
    ]
